### ISSUE TITLE
Dragging windows with iframes

### ISSUE THREAD

**Issue by 1j01** [andersevenrud/OS.js-v2#170]
This affects Wolfenstein 3D and [two](https://github.com/1j01/jspaint) [applications](https://github.com/1j01/audio-editor) that I might try to integrate into OS.js (and maybe Firefox Marketplace apps?)

This can be solved like so:
```css
application-window[data-hint="moving"] iframe {
	pointer-events: none;
}
```
(Maybe you don't want to use `data-hint`, though, I don't know)
