### ISSUE TITLE
Scroolbar

### ISSUE THREAD

**Issue by PewienTyp** [andersevenrud/OS.js-v2#62]
Example http://jsfiddle.net/7p9d9om8/

```css

           html {
                overflow: auto; // Makes the default scrollbar dissappear 
            }

            ::-webkit-scrollbar {
                width: 7px; /* Width of the vertical scrollbar button */
                height: 7px; /* Height of the horizontal scrollbar button */
            }

            ::-webkit-scrollbar-button:start:decrement,
            ::-webkit-scrollbar-button:end:increment {
                display: block;
                height: 10px; /* Height of the entiry vertical scrollbar */
                width: 10px; /* Width of the entiry horizontal scrollbar */
            }

            ::-webkit-scrollbar-button:vertical:increment {
                background-color: none; /* Background of the Scrollbar */
            }

            ::-webkit-scrollbar-button:horizontal:increment {
                background-color: none; /* Background of the Scrollbar */
            }

            ::-webkit-scrollbar-track-piece {
                background-color: none; /* Background of the track */
            }

            ::-webkit-scrollbar-thumb:vertical {
                background-color: #999; /* Background of Thumb */
                -webkit-border-radius: 3px; /* Border Radius of the Scrollbar */
            }

            ::-webkit-scrollbar-thumb:horizontal {
                background-color: #999; /* Background of Thumb */
                -webkit-border-radius: 3px; /* Border Radius of the Scrollbar */
            }
```
